### ISSUE TITLE
pkg_resources.DistributionNotFound: requests>=2.7.0,<2.8

### ISSUE THREAD

**Issue by kaushalshriyan** [fabric-bolt/fabric-bolt#175]
Hi,

cat /etc/fabric-bolt/settings.py
# ~/.fabric-bolt/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',  # We suggest PostgreSQL for optimal performance
        'NAME': 'fabric-bolt',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
        'OPTIONS': {
            'autocommit': True,
        }
    }
}
[root@ip-172-31-25-52 requests]# fabric-bolt init /etc/fabric-bolt/settings.py
Traceback (most recent call last):
  File "/usr/bin/fabric-bolt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.7.0,<2.8
[root@ip-172-31-25-52 requests]# pip freeze | grep request
requests==2.7.0
[root@ip-172-31-25-52 requests]#

Any help will be highly appreciable.

Regards,

Kaushal

**Comment by jproffitt** [comment]
Thats interesting. Did you pip install fabric-bolt version 0.1?

**Comment by kaushalshriyan** [comment]
Hi Jared Proffitt,

I did followed the below steps. Now i am facing a different issue which are as below.

[root@ip-172-31-25-52 fabric-bolt]#pip uninstall fabric-bolt
[root@ip-172-31-25-52 fabric-bolt]#pip install fabric-bolt
[root@ip-172-31-25-52 fabric-bolt]# pip freeze | grep fabric-bolt
fabric-bolt==0.1
[root@ip-172-31-25-52 fabric-bolt]# fabric-bolt init /etc/fabric-bolt/settings.py
Traceback (most recent call last):
  File "/usr/bin/fabric-bolt", line 7, in <module>
    from fabric_bolt.utils.runner import main
  File "/usr/lib/python2.6/site-packages/fabric_bolt/utils/runner.py", line 1, in <module>
    from logan.runner import run_app, configure_app
  File "/usr/lib/python2.6/site-packages/logan/runner.py", line 11, in <module>
    from django.core import management
  File "/usr/lib/python2.6/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/usr/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
  File "/usr/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
                    ^
SyntaxError: invalid syntax
[root@ip-172-31-25-52 fabric-bolt]# fabric-bolt init
Traceback (most recent call last):
  File "/usr/bin/fabric-bolt", line 7, in <module>
    from fabric_bolt.utils.runner import main
  File "/usr/lib/python2.6/site-packages/fabric_bolt/utils/runner.py", line 1, in <module>
    from logan.runner import run_app, configure_app
  File "/usr/lib/python2.6/site-packages/logan/runner.py", line 11, in <module>
    from django.core import management
  File "/usr/lib/python2.6/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/usr/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
  File "/usr/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
                    ^
SyntaxError: invalid syntax
[root@ip-172-31-25-52 fabric-bolt]#

Please suggest further.

Regards,

Kaushal

**Comment by jproffitt** [comment]
I think I may see your problem. Looks like you are using Python 2.6. FabricBolt requires python 2.7 or higher. (but not python 3) 

I will keep this issue open so that we can add that clearly in the docs.
